Add missing semicolon after get_object_id()
Missing semicolon after get_object_id() function causes compile error.

Example:
```
error: expected `;`, found `ImmutableBettingRound`
  --> src/state.rs:29:87
   |
29 |         let sub_id = get_object_id(self.obj_id, Key32(index), TYPE_ARRAY | TYPE_BYTES)
   |                                                                                       ^ help: add `;` here
30 |         ImmutableBettingRound { obj_id: sub_id }
   |         --------------------- unexpected token
```